sorting-algorithms/insertion-sort.js, sorting-algorithms/selection-sort.js
Added insertion sort and selection sort as the first two algorithms in the sorting algorithms folder. Both implemented in JavaScript.
=> Started the sorting algorithms folder.

searching/linear_search.cpp, sorting-algorithms/quick-sort.cpp
I have implemented the Quick-Sort and Linear-Search in C++.
=> Implemented linear search in C++

sorting-algorithms/mergesort.cpp
Hacktoberfest
Added mergesort implmentation in c++
=> mergesort in cpp added

sorting-algorithms/quicksort.cpp
=> New branch2

linked-list/python_linked_list.py
It's not perfect, I could have added more functions, may do it later
=> added implementation of the linked list data structure in python

searching/Linear_Search.py
Added the linear search program using Python programming language.
=> Linear Search using Python

searching/Binary Search.py, searching/Linear Search.py
=> Binary Search

problems/isPrime.cpp
The code for checking is the given number is prime or not.
=> Code for isPrime in cpp language.

problems/isPrime.c, problems/isPrime.py, stack/stack.py
=> Added isPrime solutions for Python and C

problems/isAnagram.java, problems/isAnagram.py
Simple string sort anagram check
=> Anagram check python + java

Algorithms/tower_of_hanoi.c, Algorithms/tower_of_hanoi.py, linked-list/doubly_linked_list.c, linked-list/linked_list.c, queue/circularQueue_using_Array.c, queue/circularQueue_using_LinkedList.c, queue/dequeue_using_array.c, queue/priority_queue_using_array.c, queue/queue_using_array.c, queue/queue_using_linklist.c, stack/stack_using_LinkedList.c, stack/stack_using_LinkedList.py, stack/stack_using_array.c
Implement many different data structures and algorithms.
=> Add many problems and algos

sorting-algorithms/bubble_sort.cpp
Bubble Sort implementation in CPP
=> bubble_sort.cpp

numreverse python/ numreverse.py, searching/linearSearch.java
Algorithm to reverse a numbe in python without using string.
=> numreverse

hashing/hashing.cpp, hashing/hashing.py
=> implemented hashing in c++ & python

Algorithms/KadanesAlgorithm.py
-  Implement kadane's algorithm #74
- Added Implementation of Kadane's Algorithm in Python.
=> Implement Kadane's Algorithm #74

sorting-algorithms/Counting Sort.py
Bro, this is the counting sort used in many questions of codeforces B And also on some questions in hackerrrank.
=> Create Counting Sort.py

Algorithms/Kadane's Algorithm
I have created a PR  with the solution in C++ for the issue #74 . Please review it. Thanks
=> Create Kadane's Algorithm

problems/isAnagram.js
=> isAnagram() implementation in JavaScript

fibonacci/fibonacci(Cpp).c
Algorithm forFibonacci Series upto n in C++
=> Added Fibonacci Series

Anagram/check_anagrams.cs
#53 C# code for checking if two strings are anagrams. Code Complexity is O(n).
=> Added C# code for checking anagrams

sorting-algorithms/countingsort.cpp
=> counting sort implemented in C++

problems/GCD&LCM_recursion.cpp
Takes two numbers as input and gives LCM and GCD of them.
=> added GCD&LCM_recursion.cpp to problems folder.

fibonacci/fibonacciSeries.js, fibonacci/fibonacciSeries.py
Implementation of a function which prints Fibonacci series up to a given numbers.
=> Implemented Fibonacci Series up to n

gcd.cpp
GCD and LCM using very simple logic of recursion
=> added GCD and LCM using recursion

problems/palindromeInteger.js
=> solve palindrome integer with javascript

Algorithms/Armstrong number.cpp, Algorithms/decimal to binary.cpp
=> more algorithms added

PalindromeNum.c
Algorithm to check whether a number is palindrome or not[In C]
=> Added PalindromeOfNum

searching/ternarySearch.cpp
=> added ternary search in CPP

Algorithms/BFS.cpp, sorting-algorithms/heapsort.cpp
Added the C++ implementation of HeapSort
=> Added Heapsort in C++

fibonacci/fibonacci.js
Issue #15 Implementation of Fibonacci in JS
=> Fibonacci implementation js

Algorithms/dijkstra_algo.cpp
Dijsktra algorithm implementation using CPP
=> dijkstra algorithm 

graphs/dfs.cpp
Added Solution for depth-first-search in cpp.
=> Added dfs in cpp

Arrays/maxHourGlass.py
Solution for a simple hourglass sum problem with Arrays. Implemented with Python.
=> Added hourglass Array Datastructure problem solution

Algorithms/Palindrome.cpp
Program for Checking whether a number is Palindrome or Not.
=> Created Palindrome.cpp

Algorithms/Two Pointer Algorithm
Famous Competitive Programming Question
=> Create Two Pointer Algorithm

Algorithms/FirstDuplicate.cs, Algorithms/first-duplicate.js
=> Added first duplicate in JS and C#

Mathematics/City Tour Problem
This is the Python solution for Interviewbit City Tour Problem in Math section
=> Create City Tour Problem

Algorithms/PascalTriangle
Add Pascal triangle implementation in C++
=> Add Pascal Triangle

Mathematics/fibonacci/FibonacciSequence.c
As suggested by the Author, Fixed the solution for issue #15 in the github repo
=> Fixed: Solution for Fibonacci Sequence using C(Issue #15)

Trie/Auto_Complete_using_TRIE.cpp, Trie/Implement trie (Prefix tree).cpp, Trie/Trie.cpp
- Implementation of Trie
- Prefix tree using Trie
- Auto complete feature using Trie
=> TRIE ds in c++

Algorithms/Pascal/pascals.lua
implemented Pascal's triangle in lua.
=> Pascals triangle lua

searching/binarySearch.cpp
=> added informational comments

problems/armstrongNumber.js
=> n digit armstrong number implementation in JS

Mathematics/sieve_of_eratosthenes.py
I am adding python file of Sieve of eratosthenes algorithm. Sieve of Eratosthenes is an algorithm for finding all prime numbers up to any given limit.
=> adding python file

Graph_Traversal_Algorithms/BFS&DFS.java
Added graph traversal algorithms i.e, BFS & DFS in Java.
Time Complexity= O(V+E)
Space Complexity= O(V)
Issue #139 
@ephremdeme
=> Added graph traversal algorithms in Java

Trie/trie implementation in c++ insert delete search.cpp
Added implementation of trie such as insert, delete and search operation in C++ in the Trie folder
Issue #145 
@ephremdeme Done with the changes. Happy coding :)
=> Added implementation of trie such as insert, delete and search operation in C++

Algorithms/fenwick_tree.py
Added the python fenwick tree code
Filename: fenwick_tree.py
=> fenwick tree in python

Algorithms/dikshtra.java
i have added the code of dijkstra's algorithm in java
=> added dikshtra in java

graphs/bfs.cpp
Added BFS Graph Traversal Algorithm in CPP
=> Added BFS in CPP

Algorithms/Pascal/pascalTriangle.cpp
I have made a much smaller implementation with pretty print feature
=> Pascal Triangle with Pretty Print

trie data structure/trie.cpp
@ephremdeme added trie data structure along with insertion, search, and delete operations.
=> Added trie data structure in C++

graphs/BellmanFordShortestPaths.cs
Thinking of adding more of the graphs problems
=> added the bellman ford  shortest path  in C#

DSU/DSU.cpp
This code contains implementation of DSU and how DSU can be used to find cycles in a graph.
=> Implemented DSU in C++

tree/BinarySearchTree.py
Binary Search Tree in Python #279
Added BinarySearchTree.py
=> Added BinarySearchTree.py

sorting-algorithms/BogoSort.py
- Sorting increase
- Sorting added with shuffle counter
=> Added Bogo Sort with Python

Algorithms/DijkstrasAlgorithm.cpp
Implemented Dijkstras using Set in STL
=> I have Implemented Dijkstras Algorithm using SET in STL..

Algorithms/Pascal/PascalTriangle.php
PR for issue #206
Wrote code in PHP to print pascal triangle.
=> Adding Pascal Triangle in PHP

DFS.py
Implemented Graph Traversal using DFS for Implicit Graphs
=> Implemented DFS for Implicit Graphs

BFS.py
Graph Traversal Using BFS for implicit Graphs..
=> Implemented BFS.py

Algorithms/mo.cpp
Added mo's algorithm for range minimum query, this algorithm uses square root decomposition method to update the array and answer the query.
=> Added mo's algorithm

Algorithms/Pascal/PascalsTr.go
**Program Added** -  1(PascalsTr.go)
**Issue No.**- #206
=> Added pascal Triangle

Fibonacci using recursion
Create Fibonacci using recursion #306
This code solely uses recursion. No use of loop is done.
=> Create Fibonacci using recursion

BogoSort.java, LinkedList.java, hashing/Hashing.java
=> Hashing implement

BogoSort.java, CheckAnagram.java, Kadane.java, LinkedList.java, PascalTriangle.java, SieveofEratosthenes.java, Stack.java
Circular Linked List implemented in Java
=> Circular linked list

BogoSort.java, CheckAnagram.java, Kadane.java, PascalTriangle.java, SieveofEratosthenes.java, Stack.java
Bogo Sort Algorithm implemented in Java
=> Bogo sortin java

suffixtree.py
i used python...totally basic technique and simple program...it is working fine
=> suffixtree using python

Mathematics/fibonacci/fibonacci_recursive.cs
Hey I have added a version in c#
=> fibonacci in cs

Mathematics/fibonacci/fibonacci_recursive.cpp
fibonacci_recursive.cpp implemented in c++ , #15
=> Fibonacci series using recursion 

Mathematics/fibonacci/fibonacci_recursive.py
Implemented recursive fibonacci.
=> Implemented recursive fibonacci

Algorithms/Prim.java
Closes https://github.com/ephremdeme/data-structure-and-algorithms/issues/319
=> Adding prim in java

Algorithms/Kruskal-Algo.cpp
=> Kruskal's Algorithm

Mathematics/fibo.c, Mathematics/fibo.cpp, Mathematics/fibo.java, Mathematics/fibo.py
Fibo series on C, c++,Python ,Java
=> Fibonacci series  in C, C++, Python, Java

Algorithms/Numeric/reverse-number.rkt
Adding reverse-number in Racket to Algorithms/Numeric/ for "Reverse a number without using string" #35
=> Adding reverse-number in Racket to Algorithms/Numeric/ for issue #35

sorting-algorithms/bubble_sort.py
Added implementation of bubble sort. 
Note: could you please add label hacktoberfest-accepted to the PR?
=> Added bubble sort

Other Graph Based Algorithms/Prim's.cpp
Prim's algo using c++
by shubham nag
=>  Prim's.cpp

problems/ToggleStringCharacters.cpp
- Added a program to the `problems` directory to toggle each character of a string into UPPER and LOWER case in CPP.
Input: `testTHIS123`
output: `TESTthis123`
=> Added program to toggle String Characters in CPP

Algorithms/palindrome_checker.cpp
=> can string be rearranged to form palindrome? implemented in c++

Algorithms/armstrong-Number.rkt, Mathematics/Factorial/factorial.rkt, problems/palindrome/isPalindrome?.rkt
Adding Factorial of n , recursive - in Racket for issue #347
guys, pls. do add "hacktoberfest-accepted" label when merging this PR
=> Adding Factorial of n , recursive - in Racket for issue #347

Algorithms/armstrong-Number.rkt
Adding N-digit Armstrong Number in Racket for issue #187
guys, pls. do add "hacktoberfest-accepted" label when merging this PR
=> Adding N-digit Armstrong Number in Racket for issue #187

problems/Anagram/isAnagram?.rkt
Adding Check two strings are anagrams - in Racket - for issue #53
guys, pls. do add "hacktoberfest-accepted" label when merging this PR
thanks
=> Adding Check two strings are anagrams - in Racket - for issue #53

Algorithms/Kruskal'sAlgorithm.cpp
Program of Kruskal's Algorithm in C++
=> AddKruskal'sAlgorithm

problems/reverse_list.py
Reverse a list.
Note: Please add hacktoberfest-accepted to the PR.
=> reverse a list

fibonacci/damora_fibonacci.py
=> added my own code of generating a list of fibonacci numbers

Dynamic Programming/unbounded Knapsack/(1)UnbKp.cpp, Dynamic Programming/unbounded Knapsack/(2)CoinChange1.cpp, Dynamic Programming/unbounded Knapsack/(3)CoinChange2.cpp
Unbounded Knaspsack
Coin Change I
Coin Chnage II
=> Unbounded knapsack added

stack/(10)MinStackO(1).cpp, stack/(6)MAH.cpp, stack/(7)MaxBM.cpp, stack/(8)RainwaterTrap.cpp, stack/(9)MinStackO(n).cpp
using C++ STL
Maximum area histogram (MAH)
Maximum area of boolean matrix (MAH variation)
Rainwater trapping problem
Min stack ques in O(n) space
Min stack ques in O(1) space
=> more STACK based ques

stack/(1)NGR.cpp, stack/(2)NGL.cpp, stack/(3)NSR.cpp, stack/(4)NSL.cpp, stack/(5)StockSpan.cpp
Next Greater Element to right
Next Greater Element to left
Next smaller Element to right
Next smaller Element to left
Stock span problem
=> Stack based ques and solutions added using C++ STL

Dynamic Programming/MCM/(1)MCM.cpp, Dynamic Programming/MCM/(2)PalindromePartitioning.cpp
Standard MCM DP and Palindrome Partitioning using MCM techique
=> Matrix Chain Multiplication added

problems/palindrome/palindrome.py
Added palidrome.
Note: please add hacktoberfest-accepted to the PR.
=> Added palindrome

Algorithms/remove_duplicates.py
Remove duplicates.
Note: please add hacktoberfest-accepted to the PR.
=> Remove duplicates from a list

pal.py
python program to check if number is palindrome or not ...please merge it..
for hacktoberfest
=> palindrome number check

queue/Queue_Good_code.cpp
- Functional decomposition
- Good variable names that a new programmer or newbie is able to figure out what's happening in the code.
- Spaces and formatting etc..
=> Added Queue in c++
